export const siteConfig = {
  name: "Bariq Firjatullah",
  title: "Bariq Firjatullah | Web Developer — Full-Stack & DevOps",
  shortTitle: "Bariq Firjatullah",
  description:
    "Bariq Firjatullah — Web Developer in Malang, Indonesia. Full-stack, backend, and DevOps with TypeScript, Node.js, React, Laravel, Docker, and CI/CD. Open to opportunities.",
  url: "https://bariqfirjatullah.my.id",
  locale: "en_US",
  jobTitle: "Web Developer",
  location: {
    city: "Malang",
    region: "East Java",
    country: "Indonesia",
    countryCode: "ID",
  },
  email: "bariqfirjatullah1803@gmail.com",
  phone: "+6285173001803",
  keywords: [
    "Bariq Firjatullah",
    "Web Developer",
    "Full-Stack Developer",
    "Backend Developer",
    "DevOps Engineer",
    "Portfolio",
    "TypeScript",
    "Node.js",
    "React",
    "Laravel",
    "PHP",
    "Docker",
    "CI/CD",
    "API Development",
    "Malang",
    "Indonesia",
    "Remote Developer",
    "Software Engineer",
  ],
  social: {
    linkedin: "https://www.linkedin.com/in/bariq-firjatullah",
    github: "https://github.com/bariqfirjatullah1803",
  },
  cvUrl:
    "https://drive.google.com/file/d/1gBoRcBhVxRZamP4Xq58n3PEE-RUZ8KMX/view?usp=sharing",
  googleAnalyticsId: "G-N11PP8KEM0",
} as const;

export const personJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": `${siteConfig.url}/#website`,
      url: siteConfig.url,
      name: siteConfig.name,
      description: siteConfig.description,
      inLanguage: "en-US",
      publisher: { "@id": `${siteConfig.url}/#person` },
    },
    {
      "@type": "ProfilePage",
      "@id": `${siteConfig.url}/#profilepage`,
      url: siteConfig.url,
      name: siteConfig.title,
      description: siteConfig.description,
      inLanguage: "en-US",
      isPartOf: { "@id": `${siteConfig.url}/#website` },
      about: { "@id": `${siteConfig.url}/#person` },
      mainEntity: { "@id": `${siteConfig.url}/#person` },
    },
    {
      "@type": "Person",
      "@id": `${siteConfig.url}/#person`,
      name: siteConfig.name,
      url: siteConfig.url,
      jobTitle: siteConfig.jobTitle,
      email: siteConfig.email,
      telephone: siteConfig.phone,
      description: siteConfig.description,
      address: {
        "@type": "PostalAddress",
        addressLocality: siteConfig.location.city,
        addressRegion: siteConfig.location.region,
        addressCountry: siteConfig.location.countryCode,
      },
      alumniOf: {
        "@type": "EducationalOrganization",
        name: "SMKN 4 Malang",
      },
      knowsAbout: [
        "Web Development",
        "Full-Stack Development",
        "Backend Development",
        "API Design",
        "DevOps",
        "TypeScript",
        "Node.js",
        "React",
        "Laravel",
        "Docker",
        "CI/CD",
        "MySQL",
      ],
      sameAs: [siteConfig.social.linkedin, siteConfig.social.github],
    },
  ],
};
